; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pico]
platform = raspberrypi
board = pico
framework = arduino
build_flags =
	-Wno-class-memaccess
	-Wno-address-of-packed-member
	-Wno-ignored-qualifiers
	-Wno-unused-function
lib_deps =
[env:flight_computer]
extends = env:pico
build_flags =
	-DAPOGEE_ROLE_FLIGHT_COMPUTER
	-Wno-class-memaccess
	-Wno-address-of-packed-member
	-Wno-ignored-qualifiers
	-Wno-unused-function

[env:flight_control]
extends = env:pico
build_flags =
	-DAPOGEE_ROLE_FLIGHT_CONTROL
	-Wno-class-memaccess
	-Wno-address-of-packed-member
	-Wno-ignored-qualifiers
	-Wno-unused-function

[env:telemetry]
extends = env:pico
build_flags =
	-DAPOGEE_ROLE_TELEMETRY
	-Wno-class-memaccess
	-Wno-address-of-packed-member
	-Wno-ignored-qualifiers
	-Wno-unused-function
lib_deps =
	arduino-libraries/SD@^1.3.0
	jgromes/RadioLib@^7.1.2
