; PlatformIO Project Configuration File

[env:pico]
platform = raspberrypi
board = pico
framework = arduino
build_flags =
	-Wno-address-of-packed-member
	-Wno-ignored-qualifiers
	-Wno-unused-function
lib_deps =
	arduino-libraries/SD@^1.3.0
	jgromes/RadioLib@^7.1.2
